### ISSUE TITLE
'useInsertionEffect' is not exported from 'react'

### ISSUE THREAD

**Issue by brampurnot** [raisiqueira/headless-stepper-monorepo#17]
Hello,

we are using react 17.0.2 and installed react-stepper@1.3.0 (based on an issue I saw in Github which explained we have to use 1.3.0 when using react < 18). 

During the build, we are seeing this specific error:
Attempted import error: 'useInsertionEffect' is not exported from 'react' (imported as 'useInsertionEffect').

This seems to be a hook that was introduced in React 18. Not sure if anyone else faced this issue but seems to be related to this dep. 

Bram

**Comment by brampurnot** [comment]
Seems to work when using 1.2.0!

**Comment by raisiqueira** [comment]
Hi @brampurnot can you share the error output? I'll make a demo to try to reproduce this error.

**Comment by raisiqueira** [comment]
Updated: The new version (1.5.0) is compatible with React 17 or under. Fixed on #21 

cc @brampurnot
