### ISSUE TITLE
Should onClick be possible when the current step is disabled?

### ISSUE THREAD

**Issue by kevenleone** [raisiqueira/headless-stepper-monorepo#30]
Hello 👋🏻 

Good job with this library, it's very helpful and well organized @raisiqueira. 

I was looking into examples and I had this doubt, should the user be able to click on the step, even though the step is disabled?

See:

https://github.com/raisiqueira/headless-stepper-monorepo/assets/22279592/ce19d446-5a17-4bf2-b0ae-7b3bab49e05e

Does it make sense? From my POV, it makes sense to trigger `nextStep` even if it's disabled, because the dev can control whether the step is changed, different from the user clicking on the step.

<img width="1547" alt="image" src="https://github.com/raisiqueira/headless-stepper-monorepo/assets/22279592/bb30d44c-0669-45f9-b544-7b4d980b5e34">

**Comment by kevenleone** [comment]
If it's makes sense, I can send the code and the test for it

**Comment by raisiqueira** [comment]
Hi @kevenleone, thanks for the detailed issue. Yes, you're right, I had handled this behavior in the Stepper component, but not in the hook. Could you open a pull request with this fix? Thanks.

**Comment by raisiqueira** [comment]
Solved on #31
